# Normal worker configuration for tests
bind_socket = "*:11333";

# Enable encryption key matching the controller
keypair {
    privkey = "oqqm9kkt7c1ws638cyf41apar3in1wuyx647gzrx88hhd94ehm3y";
    id = "onztu3dmoms7i7panf5mdc6hqfb3dxore8etfpftmkcy85e6jr6pujn4fgskukjfa868oceoun485rcfrywk8ihug6g1i3b8g8aj8ay";
    pubkey = "k4nz984k36xmcynm1hr9kdbn6jhcxf4ggbrb1quay7f88rpm9kay";
    type = "kex";
    algorithm = "curve25519";
    encoding = "base32";
}
